### ISSUE TITLE
大佬，考虑支持一下ThinkPHP8吧，

### ISSUE THREAD

**Issue by webersongao** [lty628/aidigu#14]
大佬，今天刚发现这个，玩了一段时间，非常精细，希望大佬可以升级到ThinkPHP8。PHP8以及TP8有更多的新特性，性能也提升不少，TP5太老了

**Comment by lty628** [comment]
> 大佬，今天刚发现这个，玩了一段时间，非常精细，希望大佬可以升级到ThinkPHP8。PHP8以及TP8有更多的新特性，性能也提升不少，TP5太老了
用户群体没有，现在也没人玩微博，未来可能会考虑升级，暂时不考虑，见谅
