### ISSUE TITLE
部署提示模块不存在:login

### ISSUE THREAD

**Issue by linkerlin** [lty628/aidigu#5]
已经在nginx里面配置了rewrite
```
        location / {
            index  index.html index.htm index.php;
            if (!-e $request_filename){
		        rewrite  ^(.*)$  /index.php?s=$1  last;   break;
	        }
        }
```
不知道是不是这里配置的不对？
有没有什么部署的文档可以参考一下？

**Comment by lty628** [comment]
nginx配置没问题的，只需将env文件配置正确就行了

**Comment by stepbystep2** [comment]
```bash
$ cat /opt/homebrew/etc/nginx/servers/aidigu.conf
server {
	location / {
            index  index.html index.htm index.php;
            if (!-e $request_filename){
		        rewrite  ^(.*)$  /index.php?s=$1  last;   break;
	        }
        }
}
```
访问`http://localhost:8888/aidigu/public`地址栏会变为`http://localhost:8888/login`，页面显示
```
Not Found

The requested URL was not found on this server.
```
PHP萌新求教

**Comment by lty628** [comment]
`server
    {
        listen 80;
        server_name www.aidigu.test;
		index index.html index.htm index.php;
        root  /data/www/aidigu/public;


		location / {
			if (!-e $request_filename){
				rewrite ^(.*)$ /index.php?s=/$1 last; break;
			}
		}
		
		location ~ [^/]\.php(/|$) {
			try_files $uri =404;
            fastcgi_split_path_info ^((?U).+\.php)(/?.+)$;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            include fastcgi_params;
        }
		
    }
`

**Comment by lty628** [comment]
@stepbystep2 绑定的目录应到 public  不能用子目录
